# Generated by Django 4.1.1 on 2022-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax',
        ),
        migrations.AlterField(
            model_name='tax',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, null=True, related_name='taxes', to='main.tax', verbose_name='Налог'),
        ),
    ]
