# Generated by Django 4.1.1 on 2022-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_discount_description_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, related_name='taxes', to='main.tax', verbose_name='Налог'),
        ),
    ]
