# Generated by Django 4.1.1 on 2022-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_item_discount_remove_item_tax_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('eur', 'eur'), ('rub', 'rub')], default='RUB', max_length=5, verbose_name='Валюта'),
        ),
    ]
